version: "3.8"

services:
  backend:
    build:
      context: .
    container_name: spring-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: graduation_spring
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
      - ./db-dumps:/docker-entrypoint-initdb.d

volumes:
  db-data: